---

- hosts: windows
  tasks:
    - name: chocolatey
      win_chocolatey:
        name: all
        state: latest

    - name: locale setting
      win_region:
        format: fr-FR
        unicode_language: fr-FR
        location: 84
        copy_settings: true
    
    - name: adobe digital editions
      win_chocolatey:
        name: adobedigitaleditions

